// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type BlogsId } from './Blogs';

/** Identifier type for public.blog_contents */
export type BlogContentsId = number & { __brand: 'BlogContentsId' };

/** Represents the table public.blog_contents */
export default interface BlogContents {
  id: BlogContentsId;

  blog_id: BlogsId;

  order: number;

  title: unknown;

  content: unknown;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table public.blog_contents */
export interface BlogContentsInitializer {
  /** Default value: nextval('blog_contents_id_seq'::regclass) */
  id?: BlogContentsId;

  blog_id: BlogsId;

  order: number;

  title: unknown;

  content: unknown;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  updated_at?: Date;
}

/** Represents the mutator for the table public.blog_contents */
export interface BlogContentsMutator {
  id?: BlogContentsId;

  blog_id?: BlogsId;

  order?: number;

  title?: unknown;

  content?: unknown;

  created_at?: Date;

  updated_at?: Date;
}
