// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type CountriesId } from './Countries';

/** Identifier type for public.cities */
export type CitiesId = number & { __brand: 'CitiesId' };

/** Represents the table public.cities */
export default interface Cities {
  id: CitiesId;

  name: string;

  partitions: unknown | null;

  country_id: CountriesId;
}

/** Represents the initializer for the table public.cities */
export interface CitiesInitializer {
  /** Default value: nextval('cities_id_seq'::regclass) */
  id?: CitiesId;

  name: string;

  partitions?: unknown | null;

  country_id: CountriesId;
}

/** Represents the mutator for the table public.cities */
export interface CitiesMutator {
  id?: CitiesId;

  name?: string;

  partitions?: unknown | null;

  country_id?: CountriesId;
}
