// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.clinic_types */
export type ClinicTypesId = number & { __brand: 'ClinicTypesId' };

/** Represents the table public.clinic_types */
export default interface ClinicTypes {
  id: ClinicTypesId;

  tr: string;

  en: string | null;
}

/** Represents the initializer for the table public.clinic_types */
export interface ClinicTypesInitializer {
  /** Default value: nextval('clinic_types_id_seq'::regclass) */
  id?: ClinicTypesId;

  tr: string;

  en?: string | null;
}

/** Represents the mutator for the table public.clinic_types */
export interface ClinicTypesMutator {
  id?: ClinicTypesId;

  tr?: string;

  en?: string | null;
}
export interface ClinicType {
  tr: string;
  en: string;

}
export interface ClinicTreatment {
  tl: number;
  usd: number;

}

