// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.clinic_users */
export type ClinicUsersId = number & { __brand: 'ClinicUsersId' };

/** Represents the table public.clinic_users */
export default interface ClinicUsers {
  id: ClinicUsersId;

  clinic_id: number;

  user_id: number;

  role: string | null;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table public.clinic_users */
export interface ClinicUsersInitializer {
  /** Default value: nextval('clinic_users_id_seq'::regclass) */
  id?: ClinicUsersId;

  clinic_id: number;

  user_id: number;

  /** Default value: 'assistant'::text */
  role?: string | null;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  updated_at?: Date;
}

/** Represents the mutator for the table public.clinic_users */
export interface ClinicUsersMutator {
  id?: ClinicUsersId;

  clinic_id?: number;

  user_id?: number;

  role?: string | null;

  created_at?: Date;

  updated_at?: Date;
}
