// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type ClinicsId } from './Clinics';
import { type TreatmentsId } from './Treatments';

/** Identifier type for public.clinic_treatments */
export type ClinicTreatmentsId = number & { __brand: 'ClinicTreatmentsId' };

/** Represents the table public.clinic_treatments */
export default interface ClinicTreatments {
  id: ClinicTreatmentsId;

  clinic_id: ClinicsId;

  treatment_id: TreatmentsId;

  is_available: boolean | null;

  price_tl: string | null;

  price_usd: string | null;
}

/** Represents the initializer for the table public.clinic_treatments */
export interface ClinicTreatmentsInitializer {
  /** Default value: nextval('clinic_treatments_id_seq'::regclass) */
  id?: ClinicTreatmentsId;

  clinic_id: ClinicsId;

  treatment_id: TreatmentsId;

  /** Default value: false */
  is_available?: boolean | null;

  price_tl?: string | null;

  price_usd?: string | null;
}

/** Represents the mutator for the table public.clinic_treatments */
export interface ClinicTreatmentsMutator {
  id?: ClinicTreatmentsId;

  clinic_id?: ClinicsId;

  treatment_id?: TreatmentsId;

  is_available?: boolean | null;

  price_tl?: string | null;

  price_usd?: string | null;
}
