// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.countries */
export type CountriesId = number & { __brand: 'CountriesId' };

/** Represents the table public.countries */
export default interface Countries {
  id: CountriesId;

  name: string;

  code: string;

  phone_code: string | null;
}

/** Represents the initializer for the table public.countries */
export interface CountriesInitializer {
  /** Default value: nextval('countries_id_seq'::regclass) */
  id?: CountriesId;

  name: string;

  code: string;

  phone_code?: string | null;
}

/** Represents the mutator for the table public.countries */
export interface CountriesMutator {
  id?: CountriesId;

  name?: string;

  code?: string;

  phone_code?: string | null;
}
