// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.dentist_branches */
export type DentistBranchesId = number & { __brand: 'DentistBranchesId' };

/** Represents the table public.dentist_branches */
export default interface DentistBranches {
  id: DentistBranchesId;

  tr: string;

  en: string ;
}

/** Represents the initializer for the table public.dentist_branches */
export interface DentistBranchesInitializer {
  /** Default value: nextval('dentist_branches_id_seq'::regclass) */
  id?: DentistBranchesId;

  tr: string;

  en?: string | null;
}

/** Represents the mutator for the table public.dentist_branches */
export interface DentistBranchesMutator {
  id?: DentistBranchesId;

  tr?: string;

  en?: string | null;
}
