// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.dentist_degrees */
export type DentistDegreesId = number & { __brand: 'DentistDegreesId' };

/** Represents the table public.dentist_degrees */
export type  DentistDegrees = {
  id: DentistDegreesId;

  tr: string;

  en: string | null;
}

/** Represents the initializer for the table public.dentist_degrees */
export interface DentistDegreesInitializer {
  /** Default value: nextval('dentist_degrees_id_seq'::regclass) */
  id?: DentistDegreesId;

  tr: string;

  en?: string | null;
}

/** Represents the mutator for the table public.dentist_degrees */
export interface DentistDegreesMutator {
  id?: DentistDegreesId;

  tr?: string;

  en?: string | null;
}


export interface DentistClinic {
  lat: number,
  lng: number,
  city: string,
  name: string,
  address: string,
  district: string
}
