// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type CitiesId } from './Cities';
import { type CountriesId } from './Countries';

/** Identifier type for public.districts */
export type DistrictsId = number & { __brand: 'DistrictsId' };

/** Represents the table public.districts */
export default interface Districts {
  id: DistrictsId;

  name: string;

  partition: string | null;

  city_id: CitiesId;

  country_id: CountriesId;
}

/** Represents the initializer for the table public.districts */
export interface DistrictsInitializer {
  /** Default value: nextval('districts_id_seq'::regclass) */
  id?: DistrictsId;

  name: string;

  partition?: string | null;

  city_id: CitiesId;

  country_id: CountriesId;
}

/** Represents the mutator for the table public.districts */
export interface DistrictsMutator {
  id?: DistrictsId;

  name?: string;

  partition?: string | null;

  city_id?: CitiesId;

  country_id?: CountriesId;
}
