// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type UsersId } from './Users';

/** Identifier type for public.favorites */
export type FavoritesId = number & { __brand: 'FavoritesId' };

/** Represents the table public.favorites */
export default interface Favorites {
  id: FavoritesId;

  subject_type: string;

  subject_id: number;

  user_id: UsersId;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table public.favorites */
export interface FavoritesInitializer {
  /** Default value: nextval('favorites_id_seq'::regclass) */
  id?: FavoritesId;

  subject_type: string;

  subject_id: number;

  user_id: UsersId;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  updated_at?: Date;
}

/** Represents the mutator for the table public.favorites */
export interface FavoritesMutator {
  id?: FavoritesId;

  subject_type?: string;

  subject_id?: number;

  user_id?: UsersId;

  created_at?: Date;

  updated_at?: Date;
}
