// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.images */
export type ImagesId = number & { __brand: 'ImagesId' };

/** Represents the table public.images */
export default interface Images {
  id: ImagesId;

  type: string;

  src: string;

  alt: string | null;

  subject_id: number;

  subject_type: string;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table public.images */
export interface ImagesInitializer {
  /** Default value: nextval('images_id_seq'::regclass) */
  id?: ImagesId;

  type: string;

  src: string;

  alt?: string | null;

  subject_id: number;

  subject_type: string;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  updated_at?: Date;
}

/** Represents the mutator for the table public.images */
export interface ImagesMutator {
  id?: ImagesId;

  type?: string;

  src?: string;

  alt?: string | null;

  subject_id?: number;

  subject_type?: string;

  created_at?: Date;

  updated_at?: Date;
}
