// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.properties */
export type PropertiesId = number & { __brand: 'PropertiesId' };

/** Represents the table public.properties */
export default interface Properties {
  id: PropertiesId;

  type: string | null;

  tr: string;

  en: string | null;
}

/** Represents the initializer for the table public.properties */
export interface PropertiesInitializer {
  /** Default value: nextval('properties_id_seq'::regclass) */
  id?: PropertiesId;

  /** Default value: 'other'::text */
  type?: string | null;

  tr: string;

  en?: string | null;
}

/** Represents the mutator for the table public.properties */
export interface PropertiesMutator {
  id?: PropertiesId;

  type?: string | null;

  tr?: string;

  en?: string | null;
}
