// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type DentistsId } from './Dentists';
import { type UsersId } from './Users';

/** Identifier type for public.questions */
export type QuestionsId = number & { __brand: 'QuestionsId' };

/** Represents the table public.questions */
export default interface Questions {
  id: QuestionsId;

  dentist_id: DentistsId;

  patient_id: UsersId;

  question: string;

  answer: string;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table public.questions */
export interface QuestionsInitializer {
  /** Default value: nextval('questions_id_seq'::regclass) */
  id?: QuestionsId;

  dentist_id: DentistsId;

  patient_id: UsersId;

  question: string;

  answer: string;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  updated_at?: Date;
}

/** Represents the mutator for the table public.questions */
export interface QuestionsMutator {
  id?: QuestionsId;

  dentist_id?: DentistsId;

  patient_id?: UsersId;

  question?: string;

  answer?: string;

  created_at?: Date;

  updated_at?: Date;
}
