// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type UsersId } from './Users';

/** Identifier type for public.reviews */
export type ReviewsId = number & { __brand: 'ReviewsId' };

/** Represents the table public.reviews */
export default interface Reviews {
  id: ReviewsId;

  subject_type: string;

  subject_id: number;

  user_id: UsersId;

  body: string | null;

  rate: string | null;

  confirmed_at: Date | null;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table public.reviews */
export interface ReviewsInitializer {
  /** Default value: nextval('reviews_id_seq'::regclass) */
  id?: ReviewsId;

  subject_type: string;

  subject_id: number;

  user_id: UsersId;

  body?: string | null;

  /** Default value: '5'::numeric */
  rate?: string | null;

  confirmed_at?: Date | null;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  updated_at?: Date;
}

/** Represents the mutator for the table public.reviews */
export interface ReviewsMutator {
  id?: ReviewsId;

  subject_type?: string;

  subject_id?: number;

  user_id?: UsersId;

  body?: string | null;

  rate?: string | null;

  confirmed_at?: Date | null;

  created_at?: Date;

  updated_at?: Date;
}
