// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.users */
export type UsersId = number & { __brand: 'UsersId' };

/** Represents the table public.users */
export default interface Users {
  id: UsersId;

  role: string;

  name: string;

  last_name: string;

  identity_no: string | null;

  passport_no: string | null;

  birth_date: Date | null;

  gender: string | null;

  language: string | null;

  phone: string | null;

  email: string | null;

  phone_verified_at: Date | null;

  email_verified_at: Date | null;

  dtsanalpos_id: number | null;

  password: string | null;

  ref_ids: string | null;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table public.users */
export interface UsersInitializer {
  /** Default value: nextval('users_id_seq'::regclass) */
  id?: UsersId;

  /** Default value: 'not_defined'::text */
  role?: string;

  name: string;

  last_name: string;

  identity_no?: string | null;

  passport_no?: string | null;

  birth_date?: Date | null;

  gender?: string | null;

  /** Default value: 'tr'::character varying */
  language?: string | null;

  phone?: string | null;

  email?: string | null;

  phone_verified_at?: Date | null;

  email_verified_at?: Date | null;

  dtsanalpos_id?: number | null;

  password?: string | null;

  /** Default value: ''::text */
  ref_ids?: string | null;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  updated_at?: Date;
}

/** Represents the mutator for the table public.users */
export interface UsersMutator {
  id?: UsersId;

  role?: string;

  name?: string;

  last_name?: string;

  identity_no?: string | null;

  passport_no?: string | null;

  birth_date?: Date | null;

  gender?: string | null;

  language?: string | null;

  phone?: string | null;

  email?: string | null;

  phone_verified_at?: Date | null;

  email_verified_at?: Date | null;

  dtsanalpos_id?: number | null;

  password?: string | null;

  ref_ids?: string | null;

  created_at?: Date;

  updated_at?: Date;
}
