const termsClinicRegister = (
    <div>
        
        <h2 className="border-l-4 border-solid border-gray-400 pl-2 font-medium text-xl mt-5 mb-3">1.TARAFLAR</h2> 
        <p className="mb-1 pb-1 text-md">Bu Klinik Çerçeve Lisans Sözleşmesi (Sözleşme), Atatürk Mah. Ertuğrul Gazi Sk. Metropol Istanbul Sitesi C1 Blok No: 2B İç Kapı No: 135 Ataşehir / İstanbul adresinde faaliyet gösteren Diştedavim Teknoloji Hizmetleri Anonim Şirketi (Diştedavim) ile aşağıda bilgilerine yer verilen Klinik arasında aşağıdaki şart ve koşullarla mutabık çevrimiçi şekilde akdedilmiştir. Bu Sözleşme’de Diştedavim ve Klinik ayrı ayrı <b>“Taraf”</b> ve birlikte <b>“Taraflar”</b> olarak adlandırılacaktır.</p>

        <h2 className="border-l-4 border-solid border-gray-400 pl-2 font-medium text-xl mt-5 mb-3">2.TANIMLAR</h2> 
        <p className="mb-1 pb-1 text-md"><b>Süper Kullanıcı:</b> Klinik tarafından belirlenen, Hizmetler’in sunulması amacıyla Platform’a erişmesi için Diştedavim tarafından kendisine kullanıcı adı tahsis edilen, bu Sözleşme’de yer alan Süper Kullanıcı işlemlerini yapabilen ve Sözleşme’yi Klinik adına ve hesabına onaylayan kişi veya kişileri,</p>

        <p className="mb-1 pb-1 text-md"><b>Hizmet/ler:</b> Diştedavim tarafından, Klinik’in klinik yönetim, randevu yönetim, hasta takibi ve online görüşme işlemlerini yönetmesine imkân sağlamak amacıyla Platform üzerinden Klinik’e sunulan teknolojik çözümlerden biri ve/veya tamamı;</p>

        <p className="mb-1 pb-1 text-md"><b>Kişisel Veri:</b> 6698 sayılı Kişisel Verilerin Korunması Kanunu’nda “kimliği belirli veya belirlenebilir gerçek kişiye ilişkin her türlü bilgi” olarak tanımlanan veri/verileri,</p>
        
        <p className="mb-1 pb-1 text-md"><b>Kullanıcılar:</b> Platform’a erişim sağlayarak Hizmetler’den yararlanan tüm Klinik çalışanlarını,</p>

        <p className="mb-1 pb-1 text-md"><b>Platform:</b> Klinik’e Hizmetler’den yararlanabilmek adına kullanım hakkı tanınan ve Diştedavim’in sahibi olduğu, <a href="https://distedavim.com">https://distedavim.com</a> ve/veya Diştedavim mobil uygulamasını ifade eder. </p>

        <h2 className="border-l-4 border-solid border-gray-400 pl-2 font-medium text-xl mt-5 mb-3">3.SÖZLEŞME’NİN KONUSU</h2>
        <p className="mb-1 pb-1 text-md"><b>3.1</b> Klinik’e Hizmetler’den yararlanabilmek adına kullanım hakkı tanınan ve Diştedavim’in sahibi olduğu, <a href="https://distedavim.com">https://distedavim.com</a> ve/veya Diştedavim mobil uygulamasını ifade eder. </p> 

        <p className="mb-1 pb-1 text-md"><b>3.2</b> Kullanım Koşulları ve Gizlilik Politikası ve Kişisel Veriler Metni bu Sözleşme’nin ayrılmaz bir parçasıdır ve bu metinlerde yer alan hükümler bu Sözleşme’den bağımsız olarak uygun olduğu ölçüde geçerliliğini koruyacaktır. Bu Sözleşme’de açıkça tanımlanmayan ve büyük harfle başlatılan kelimeler, Kullanım Koşulları ve/veya Gizlilik Politikası ve Kişisel Veriler Metni’nde kendisine atfedilen anlamı taşıyacaktır. </p> 

        <p className="mb-1 pb-1 text-md"><b>3.3</b> Kullanım Koşulları ve Gizlilik Politikası ve Kişisel Veriler Metni bu Sözleşme’nin ayrılmaz bir parçasıdır ve bu metinlerde yer alan hükümler bu Sözleşme’den bağımsız olarak uygun olduğu ölçüde geçerliliğini koruyacaktır. Bu Sözleşme’de açıkça tanımlanmayan ve büyük harfle başlatılan kelimeler, Kullanım Koşulları ve/veya Gizlilik Politikası ve Kişisel Veriler Metni’nde kendisine atfedilen anlamı taşıyacaktır.</p>
        
        <p className="mb-1 pb-1 text-md"><b>3.4</b> Diştedavim Platform’a erişen/üye olan herhangi bir Klinik için aracılık veya reklam faaliyeti yürütmemekte olup, yalnızca Platform kullanıcıları arasında iletişimin sağlanması için gerekli teknik altyapıyı sağlamaktadır.</p>

        <p className="mb-1 pb-1 text-md"><b>3.5</b> Diştedavim, Klinikler için ihtiyaç duyulan dijital ve teknolojik çözümleri üreten ve geliştiren bir teknoloji şirketidir. Bu kapsamda Diştedavim, Sözleşme süresi boyunca, Klinik’e Platform üzerinden; Platform’a erişim hakkı tanıyarak (Software as a Service- Bir Hizmet olarak Yazılım) Hizmetleri sunacaktır. Diştedavim’in sunduğu Hizmetler’in amacı, Klinikler’in Hizmetler ile Platform üzerinden klinik yönetim işleri, randevu takipleri ve hasta takipleri ve çevrimiçi görüşme imkanı gibi çeşitli hizmetleri yönetmesine imkân sağlamaktan ibarettir. </p>

        <h2 className="border-l-4 border-solid border-gray-400 pl-2 font-medium text-xl mt-5 mb-3">4.HİZMETLER’E DAİR TARAFLAR’IN HAK VE YÜKÜMLÜLÜKLERİ </h2>
        <p className="mb-1 pb-1 text-md"><b>4.1</b> Diştedavim, Klinikler için ihtiyaç duyulan dijital ve teknolojik çözümleri üreten ve geliştiren bir teknoloji şirketidir. Bu kapsamda Diştedavim, Sözleşme süresi boyunca, Klinik’e Platform üzerinden; Platform’a erişim hakkı tanıyarak (Software as a Service- Bir Hizmet olarak Yazılım) Hizmetleri sunacaktır. Diştedavim’in sunduğu Hizmetler’in amacı, Klinikler’in Hizmetler ile Platform üzerinden klinik yönetim işleri, randevu takipleri ve hasta takipleri ve çevrimiçi görüşme imkanı gibi çeşitli hizmetleri yönetmesine imkân sağlamaktan ibarettir. </p> 

        <p className="mb-1 pb-1 text-md"><b>4.2</b> Platform’a giriş yapan Süper Kullanıcı, bu Sözleşme uyarınca Klinik için farklı Kullanıcı hesapları açarak Kullanıcılar atayabilecektir. Platform’u kullanacak Süper Kullanıcı ve diğer Kullanıcılar’ın şifreleri, kullanıcı adları, bunlara tanınan kullanıcı yetkilerinin gerekliliği gibi konularda tüm sorumluluk Klinik’e ait olup; Diştedavim’in Kullanıcılar ve hesaplarla ilgili herhangi bir denetim ve gözetim yükümlülüğü bulunmamaktadır. Bu konularla ilgili Diştedavim’e hiçbir sorumluluk yüklenemez.</p> 

        <h2 className="border-l-4 border-solid border-gray-400 pl-2 font-medium text-xl mt-5 mb-3">5.HİZMETLER’E DAİR TARAFLAR’IN HAK VE YÜKÜMLÜLÜKLERİ </h2>
        <p className="mb-1 pb-1 text-md"><b>5.1</b> Klinik, bu Sözleşme dâhilinde kendisine sağlanacak Hizmetler’den sadece kendisinin yararlanacağını, söz konusu Hizmet’i; kendi tüzel kişiliği nezdinde yetkili kıldığı Süper Kullanıcı ve Süper Kullanıcı’nın yetkilendirdiği Kullanıcılar hariç diğer kişi, kurum ve kuruluşlara kullandıramayacağını ve devredemeyeceğini, başkasına kiralayamayacağını, satamayacağını kabul, beyan ve taahhüt eder.</p> 

        <p className="mb-1 pb-1 text-md"><b>5.2</b> Diştedavim, Hizmetler’in kapsamını ve şartlarını, Platform’da duyurmak da dahil olmak üzere tercih edeceği iletişim kanallarıyla Klinik ve diğer kullanıcılara bildirerek/duyurarak değiştirme hakkını saklı tutar. Klinik, Platform ve Diştedavim tarafından kullanılabilecek diğer iletişim kanallarını devamlı surette takip etmekle ve Diştedavim tarafından sağlanacak bilgi ve belgelere uygun olarak Platform’u kullanıp Hizmetler’den yararlanmakla yükümlüdür. </p>
        
        <p className="mb-1 pb-1 text-md"><b>5.3</b> Diştedavim, Hizmetler’i sunabilmek için, Platform üzerinden Klinik’in açık ticaret unvanı, markası, logosu, açık adresi, telefon numarası, Platform’a eklenmesi için Klinik tarafından kendisi ile paylaşılan hekim bilgileri ve görsellerini Platform’da paylaşmak zorundadır. Klinik bunu bilir ve kabul eder.  Hizmetler’in kapsamı ve şartlarındaki değişiklikler doğrultusunda Diştedavim ek bilgi ve belgeleri Klinik’ten talep edebilir, mevcut bilgi ve belgelerin güncellenmesini Klinik’ten isteyebilir. Aksi takdirde Hizmet’in gereği gibi sunulamamasından Diştedavim’in sorumlu olmadığını Klinik peşinen kabul eder.</p>
        
        <p className="mb-1 pb-1 text-md"><b>5.4</b> Klinik, 1219 sayılı Tababet ve Şuabatı San’atlarının Tarzı İcrasına Dair Kanun, Ağız ve Diş Sağlığı Hizmeti Sunulan Özel Sağlık Kuruluşları Hakkında Yönetmelik ve Uzaktan Sağlık Hizmetlerinin Sunumu Hakkında Yönetmelik başta olmak üzere ilgili mevzuat kapsamında hastalara sunacağı her türlü hizmetten münhasıran ve münferiden sorumludur. Bu kapsamda Diştedavim, Klinik’in hastalarına sunacağı herhangi bir tıbbi tanı, teşhis, tedaviye dair bir sorumluluk üstlenmez ve herhangi bir talep veya iddianın muhatabı değildir. </p>

        <p className="mb-1 pb-1 text-md"><b>5.5</b> Diştedavim, Klinik’in hastalarına uzaktan sağlık hizmetleri sunabilmesi için, T.C. Sağlık Bakanlığı nezdinde lisanslı Uzaktan Sağlık Bilgi Sistemi olup; Platform üzerinden uzaktan sağlık hizmetlerinin sunulabilmesi için çeşitli teknolojik olanaklar sağlamaktadır. Klinik, ilgili uzaktan sağlık hizmetlerinin herhangi birini sunabilmek amacıyla Platform’u kullanması halinde, Sağlık Bakanlığı tarafından yayımlanan Uzaktan Sağlık Hizmetlerinin Sunumu Hakkında Yönetmelik ve ilgili mevzuat kapsamında alması gereken izinler veya gerçekleştirmesi gereken bildirimler varsa, bunların gerçekleştirilmesi/alınması münhasıran ve münferiden Klinik’e aittir. Diştedavim’in Platform vasıtasıyla Klinik’e bu teknolojik imkânı sağlaması, Klinik’in mevzuata uyumluluğunu kontrol etme yükümlülüğü olduğunu göstermez. Bu kapsamda her türlü sorumluluk doğrudan Klinik’e aittir. </p>

        <p className="mb-1 pb-1 text-md"><b>5.6</b> Diştedavim, Klinik’in hastalarına uzaktan sağlık hizmetleri sunabilmesi için, T.C. Sağlık Bakanlığı nezdinde lisanslı Uzaktan Sağlık Bilgi Sistemi olup; Platform üzerinden uzaktan sağlık hizmetlerinin sunulabilmesi için çeşitli teknolojik olanaklar sağlamaktadır. Klinik, ilgili uzaktan sağlık hizmetlerinin herhangi birini sunabilmek amacıyla Platform’u kullanması halinde, Sağlık Bakanlığı tarafından yayımlanan Uzaktan Sağlık Hizmetlerinin Sunumu Hakkında Yönetmelik ve ilgili mevzuat kapsamında alması gereken izinler veya gerçekleştirmesi gereken bildirimler varsa, bunların gerçekleştirilmesi/alınması münhasıran ve münferiden Klinik’e aittir. Diştedavim’in Platform vasıtasıyla Klinik’e bu teknolojik imkânı sağlaması, Klinik’in mevzuata uyumluluğunu kontrol etme yükümlülüğü olduğunu göstermez. Bu kapsamda her türlü sorumluluk doğrudan Klinik’e aittir. </p>

        <p className="mb-1 pb-1 text-md"><b>5.8</b> Diştedavim, her türlü önlem ve tedbiri almış olmasına rağmen, kendisinin ulusal veya uluslararası yasalar, yetkili makamlarca yayımlanan tebliğ, genelge ve esaslar gereğince başka türlü hareket etmesini gerektirecek haklı nedenlerin mevcut olduğu durumlarda sunulan Hizmetler’in kapsamını daraltabilir, tamamen durdurabilir. Klinik, bu nedenlerle uğrayabileceği zarar ve kayıplar için hiçbir şekilde Diştedavim’a rücu talebinde bulunmayacağını peşinen kabul, beyan ve taahhüt eder.</p>

        <p className="mb-1 pb-1 text-md"><b>5.9</b> Platform’daki Hizmetler Klinik bazlı değişmemektedir. Bu kapsamda Platform kullandırılarak sunulan Hizmetler “olduğu gibi” sunulmakta olup Diştedavim; (i) Klinik’in Hizmet’i ve/veya Platform’u yanlış kullanmasından ve/veya Klinik’in yükümlülüklerini yerine getirmemesi sebebiyle ortaya çıkacak zararlardan, (ii) Hizmetler’in sunulması veya Platform’un kullanılmasından dolayı, kendisinin kastı veya ağır kusur halleri hariç, ortaya çıkan veri kaybı veya hatalardan, (iii) donanım, yazılım, ve ağ ilişkili işlevlerden ve bu nedenle ortaya çıkacak kendi kastı olmayan arızalardan, (iv) iletişim ağı (network) tasarım ve bağlantı hatalarından, (v) Klinik’in yazılım, donanım veya ağda yahut üçüncü parti uygulamalarda barındırdığı verilerin Hizmetler’e veya Platform’a ilişkin girdileri hatalı veya eksik hale getirmesi sebebiyle Hizmetler ve Platform sonucu ortaya çıkabilecek herhangi bir zarar veya ziyandan yahut veri kaybından veya verinin yanlış yorumlanmasından sorumlu değildir. </p>
        
        <p className="mb-1 pb-1 text-md"><b>5.10</b> Diştedavim, Platform üzerinden sunduğu Hizmetler’in sürekli aktif ve erişilebilir olacağına dair hiçbir garanti vermemektedir ve herhangi bir sebepten dolayı Platform üzerinden sunulan Hizmetler’de meydana gelen aksaklıklar konusunda hiçbir şekilde sorumluluk kabul etmez. Diştedavim tek taraflı olarak ve herhangi bir bildirimde bulunmaksızın Platform üzerinden yeni Hizmetler sunabilir, Hizmetler’i sunmayı bırakabilir, kısmen veya tamamen değiştirebilir. </p>

        <h2 className="border-l-4 border-solid border-gray-400 pl-2 font-medium text-xl mt-5 mb-3">6.FİKRİ MÜLKİYET</h2>

        <p className="mb-1 pb-1 text-md"><b>6.1</b> Platform vasıtasıyla Klinik’e sağlanan Lisans, Hizmetler kapsamında bedelsiz olarak sağlanmakta olup Klinik’in Hizmetler kapsamında olmayan ve Platform üzerinden sağlanan ödeme ve tahsilat takibi hizmetinden yararlanmak istemesi durumunda, ek şart ve ücretlendirmelere tabi olacaktır.</p>
        
        <p className="mb-1 pb-1 text-md"><b>6.2</b> Diştedavim, Hizmetler‘in kapsamında değişiklik yapma hakkı saklı olup, Hizmetler’i bedel karşılığında sunmaya da karar verebilir. Böyle bir durumda Diştedavim’in Hizmetler’i ücretlendirmesi veya Hizmetler’in kapsamında değişiklik gerçekleştirmesi durumunda Diştedavim, bu değişikliği Klinik’e e-posta yoluyla veya Klinik’in Platform’daki arayüzünde görünebilir bir şekilde Klinik’e duyurur. Taraflar, değişikliklerin yayınlandığı ve/veya bildirildiği tarihte geçerli olacağını kabul, beyan ve taahhüt eder.  Bu duyurunun/bildirimin ardından Klinik’in Platform’u kullanmayı devam etmesi halinde Klinik’in bu değişiklikleri açıkça onayladığı kabul edilecektir. Klinik, bu değişiklik ve güncellemeleri takip etmekle yükümlüdür.</p>

        <p className="mb-1 pb-1 text-md"><b>6.3</b> Platform, sunulan Hizmetler’e ilişkin mevzuattaki değişiklikler sebebiyle zorunlu olarak güncellenebilir veya versiyon güncellenebilir. Böyle bir durumda Diştedavim, ilgili geliştirme/güncelleme sebebiyle Klinik’e ek ücretlendirme yapabilme hakkını saklı tutar. </p>

        <h2 className="border-l-4 border-solid border-gray-400 pl-2 font-medium text-xl mt-5 mb-3">7.SÖZLEŞME’NİN SÜRESİ VE FESHİ</h2>
        <p className="mb-1 pb-1 text-md"><b>7.1</b> İşbu Sözleşme çerçevesinde Diştedavim, Platform üzerinde Türkiye sınırları dâhilinde, sadece Platform’un kullanma amacına uygun olarak Klinik’e bu Sözleşme süresince geçerli ve münhasır olmayan, bu Sözleşme hükümlerine uygun olarak bedelsiz, devredilemeyen ve alt lisans verilemeyen bir lisans (basit ruhsat) hakkı tanımaktadır (Lisans). Sözleşme kapsamında verilen Lisans, bu Sözleşme’de ayrıca ücrete tabi olduğu belirtilen veya ilgili mevzuat kapsamında ayrıca ücretlendirmeye tabi tutulabilecek herhangi bir hususu içermez. </p>
        
        <p className="mb-1 pb-1 text-md"><b>7.2</b> İşbu Sözleşme kapsamında, Platform’un kaynak kodları başta olmak üzere, Platform’a ilişkin her türlü bilgi ve belgeye ilişkin tüm fikri ve sınai haklar, patent, marka ve eser haklarının ilgili mevzuat kapsamında münhasır sahibi Diştedavim’dir. Diştedavim, Platform’u sadece bu Sözleşme’de belirlenen kullanım amaçlarına uygun kullanması için Klinik’e kullanım hakkı tanımıştır. Klinik Platform’u bu amaçlar dışında kullanamaz; üçüncü şahıslara kiralayamaz, kullandıramaz, alt lisans veremez, satamaz, devredemez. Klinik, herhangi bir şekilde Platform’un kaynak kodlarına ulaşmak, tersine mühendislik yapmak, Platform’un nihai versiyonlarından önceki versiyonlarına ulaşmak gibi Platform’un fikri haklarına müdahale niteliğindeki fiilleri gerçekleştiremez.</p>

        <h2 className="border-l-4 border-solid border-gray-400 pl-2 font-medium text-xl mt-5 mb-3">8.SÖZLEŞME’NİN SÜRESİ VE FESHİ</h2>
        <p className="mb-1 pb-1 text-md"><b>8.1</b> Bu Sözleşme, çevrimiçi şekilde Klinik tarafından onaylandığı tarihte yürürlüğe girecek ve Taraflarca sona erdirilmedikçe yürürlükte kalacaktır. Klinik’in yetkilisi olan Süper Kullanıcı, Sözleşme’yi bütünüyle anladığını, bu Sözleşme’yi Klinik adına imzalamaya yetkili olduğunu beyan ve taahhüt eder. Bu sözleşme akdedildikten sonra dilediği zamanda Diştedavim, bu hususu denetlemek için kendi uygun gördüğü yöntemlerle Klinik’ten ve/veya Süper Kullanıcı’dan, Süper Kullanıcı’nın Klinik adına bu Sözleşme’yi akdetme yetkisi olduğuna dair çeşitli ispat edici bilgi ve belgeleri talep edebilecektir. Klinik’in ve/veya Süper Kullanıcı’nın Diştedavim’in bu madde kapsamındaki taleplerini yerine getirmemesi durumunda; Diştedavim’in Platform’un kullanılmasını tamamen veya kısmen durdurma ve Klinik’e bu Sözleşme kapsamında tanınan Lisans’ı derhal sona erdirme hakkı saklıdır.</p>

        <p className="mb-1 pb-1 text-md"><b>8.2</b> Diştedavim, bu Sözleşme’yi sebep göstermeksizin her zaman ve önceden süre vermesine gerek olmaksızın, tazminatsız sona erdirebilir, Klinik’in ve Kullanıcı’larının kullanım yetkilerine son verebilir, Klinik’in Platform’dan yararlanmasını kısıtlayabilir veya Hizmetler’den yararlanmasına son verebilir. Klinik de Sözleşmeyi herhangi başkaca bir sebep göstermeksizin sona erdirebilir.  Sona erdirme bildiriminin alındığının Diştedavim tarafından alındığının teyit edildiği tarihte Sözleşme Klinik tarafından sona erdirilmiş olacaktır. </p>

        <p className="mb-1 pb-1 text-md"><b>8.3</b> Sözleşme’nin sona erme nedenine bakılmaksızın, bu Sözleşme’nin sona erdiği tarih itibariyle Diştedavim’in bu Sözleşme kapsamında Klinik’e ve Kullanıcılar’a tanıdığı Platform’a ilişkin Lisans da kendiliğinden sona erer ve Klinik, bu Sözleşmeye dayanarak Diştedavim’den herhangi bir hizmet talebinde bulunamaz. </p>

        <p className="mb-1 pb-1 text-md"><b>8.4</b> Diştedavim, Klinik tarafından onaylanan Kullanım Koşulları’nda yer verilen Sözleşme’nin haklı nedenle feshine sebep oluşturacak ihlaller, Klinik’in hukuka ve ahlaka aykırı faaliyetleri veya herhangi bir Platform kullanıcısının Platformdaki hizmetlerden yararlanmasını zedeleme ihtimali bulunan eylemler sebebiyle Sözleşme’yi sona erdirme hakkını saklı tutar. </p>

        <p className="mb-1 pb-1 text-md"><b>8.5</b> Klinik’in bu Sözleşme’de belirtilen yükümlülüklerine aykırı hareket etmesi, söz konusu olduğunda Hizmet bedellerini ödememesi, eksik veya geç ödemesi, hukuka veya ahlaka aykırı bir faaliyette bulunulduğunun tespiti halinde Diştedavim, bu Sözleşme’yi ve Kullanıcı Sözleşmesi’ni bildirimsiz ve tazminatsız olarak feshetme, Klinik’in hesaplarına erişimi süreli veya süresiz olarak askıya alma ve/veya sonlandırma, Klinik’in Platform’dan yararlanmasını geçici veya kalıcı olarak engelleme hakkına sahiptir. Bunlara ek olarak, Diştedavim’in hukuki ve cezai yollara başvurma hakkı saklıdır. </p>

        <h2 className="border-l-4 border-solid border-gray-400 pl-2 font-medium text-xl mt-5 mb-3">9.KİŞİSEL VERİLERİN KORUNMASI</h2>
        <p className="mb-1 pb-1 text-md"><b>9.1</b> Taraflar, bu Sözleşme süresiyle sınırlı olmaksızın, Sözleşme’den kaynaklanan yükümlülüklerinin yerine getirilmesi ile ilgili olarak Kişisel Verilerin Korunması Kanunu ve ikincil düzenlemelere uygun şekilde hareket edeceklerini kabul ve beyan eder. </p>
        <p className="mb-1 pb-1 text-md"><b>9.2</b> Diştedavim, Klinik’te tedavi olmak isteyen hastalara ilişkin, hastaların doğrudan Platform vasıtasıyla kendisiyle paylaştığı veya Platform kullanımı sebebiyle işlediği Kişisel Veriler dışında; hiçbir Kişisel Veri işlemez. Diştedavim’in veri sorumlusu sıfatıyla kişisel veri işleme faaliyetlerine ilişkin Gizlilik Politikası ve Kişisel Veri Metni’nde gerekli aydınlatma yapılmakta olup, bunun dışında kalan tüm kişisel verilere ilişkin sorumluluk veri sorumlusu sıfatıyla Klinik’tedir. Bu kapsamda Klinik, Kişisel Verilerin Korunması Kanunu ve ikincil mevzuat kapsamında veri sorumlusunun yerine getirmesi gereken yükümlülükler ve Kişisel Verileri Koruma Kurumu tarafından veri sorumlusundan yerine getirilmesi beklenebilecek tüm idari ve teknik tedbirlerden münferiden sorumludur. </p>

        <p className="mb-1 pb-1 text-md"><b>9.3</b> Klinik’in ve/veya Kullanıcılar’ın Uzaktan Sağlık Hizmetlerinin Sunumu Hakkında Yönetmelik (Yönetmelik) uyarınca Platform’u kullanarak “uzaktan sağlık hizmeti” sunması durumunda T.C. Sağlık Bakanlığı ile kişisel veri paylaşımına dair düzenlemeler başta olmak üzere Yönetmelik’te belirtilen kişisel verilere ilişkin bütün düzenlemelere uymakla yükümlü olup, bu hususu bildiğini ve ilgili düzenlemelere uygun şekilde hareket edeceğini kabul ve beyan eder. </p>

        <p className="mb-1 pb-1 text-md"><b>9.4</b> Klinik ve/veya Kullanıcılar tarafından Platform kullanılarak Yönetmelik kapsamında “uzaktan sağlık hizmeti” sunulduğu her durumda işlenen bütün Kişisel Veriler’e ilişkin Kanun uyarınca veri sorumluluğu sıfatı Klinik’e ait olup, Diştedavim’in bu kapsamda herhangi bir Kişisel Veri’ye erişmesi söz konusu olduğunda Klinik’in veri işleyeni sıfatına sahip olacaktır. Bu kapsamda Diştedavim işbu hizmet kapsamındaki herhangi bir talep veya iddianın muhatabı değildir. </p>
        
        <p className="mb-1 pb-1 text-md"><b>9.5</b> Klinik, Platform’da bilgilerine yer verilebilmesi için kendi bordrolu veya anlaşmalı diş hekimlerinin bilgilerini ve Kişisel Veriler’ini Diştedavim’e aktaracaktır. Ayrıca Klinik, Platform’un yönetilmesi amacıyla Platform’u kendi farklı çalışanlarına da kullandırtabilir ve bu kişilerin Platform’u kullanması için onları görevlendirmek yetkisine sahip durumdadır. Bu Kişisel Veriler dahil, Klinik tarafından Diştedavim’e aktarılan tüm Kişisel Veriler’e ilişkin Klinik; (i) Kişisel Verilerin Korunması Kanunu ve ilgili özel düzenlemelerde belirtilen usul ve esaslara riayet ettiğini;  (ii) Kişisel Veriler’in işlenme şartlarını karşıladığını; (iii) Kişisel Veriler’in üçüncü kişilere ve yurt dışına aktarılması dahil olmak üzere, gerekli bütün açık rıza taahhüt ve onayların ilgili mevzuatta belirtilen şekil ve şartlara uygun olarak aldığını ve diğer teknik gereklilikleri yerine getirdiğini; (iv) aydınlatma yükümlülüğünü yerine getirdiğini; (v) Kişisel Veriler’in silinmesi, yok edilmesi veya anonim hâle getirilmesine ilişkin gereklilikleri yerine getirdiğini ve getireceğini; (vi) aktarılan bütün bilgi ve belgelerin güncel olduğunu ve (vii) Kişisel Veriler’in nihai olarak Kanun’a ve ilgili özel düzenlemelere uygun olarak temin edildiğini kabul, beyan ve taahhüt eder. 
        </p>

        <h2 className="border-l-4 border-solid border-gray-400 pl-2 font-medium text-xl mt-5 mb-3">10.GİZLİLİK</h2>
        <p className="mb-1 pb-1 text-md"><b>10.1</b> Taraflar, Sözleşme görüşmelerinde, bu Sözleşme süresince ve Sözleşme herhangi bir nedenle sona erdikten sonra süresiz olarak, bu Sözleşme konusunun gerçekleşip gerçekleşmediğine bakılmaksızın ve birbirlerinin önceden yazılı onayını almaksızın kendisinin, çalışanlarının, varsa iştiraklerinin ve bunların temsilcilerinin bu Sözleşme’nin ifası esnasında ve ifasıyla ilgili olarak edindiği/edineceği ticari sırlar başta olmak üzere, know-how da dâhil yazılı veya sözlü her türlü bilgi, basılı veya elektronik ortamdaki dokümanı ve bunlarla sınırlı kalmaksızın birbirleri ile ilgili edindiği her türlü gizli bilgileri üçüncü kişilere herhangi bir biçimde açıklamayacağını veya üçüncü kişilerin erişimine izin vermeyeceğini, yaymayacağını, yayınlamayacağını, bunları büyük bir gizlilik içinde koruyacağını ve ifşa etmeyeceğini kabul, beyan ve taahhüt eder.</p>
        
        <p className="mb-1 pb-1 text-md"><b>10.2</b> Sözleşme’nin herhangi bir sebeple sona ermesi halinde, Klinik Platform’a ait her türlü veriyi elektronik ortamlarından gecikmeksizin sileceğini ve imha edeceğini, silinmesi mümkün olmayan ve fikri mülkiyete konu olabilecek veya diğer bilgi ve belgeleri derhal Diştedavim’e iade edeceğini kabul, beyan ve taahhüt eder. </p>

        <h2 className="border-l-4 border-solid border-gray-400 pl-2 font-medium text-xl mt-5 mb-3">11.DİĞER HÜKÜMLER</h2>
        <p className="mb-1 pb-1 text-md"><b>11.1</b> Klinik, önceden verilmiş yazılı ön onay olmaksızın bu Sözleşme’den kaynaklanan hak ve yükümlülüklerini üçüncü kişilere veya herhangi bir kurum/kuruluşa devir veya temlik edemez. Bununla birlikte, Diştedavim’in bu Sözleşme’de düzenlenen hususlarda üçüncü kişileri yetkilendirme ve/veya üçüncü kişilerden destek alma hakkı saklıdır. </p>
        
        <p className="mb-1 pb-1 text-md"><b>11.2</b> Klinik, Diştedavim’in tanıtımı amacı ile Diştedavim tarafından oluşturulan kullanıcı listesine dâhil edilmesini kabul eder. Bu kapsamda Diştedavim, Klinik’in ismini/ticaret unvanını başarı hikâyesi, röportaj, tanıtım ve gerekli gördüğü takdirde kamu açıklamalarında pazarlama amacıyla kullanabilir.</p>
        
        <p className="mb-1 pb-1 text-md"><b>11.3</b> Taraflar bu Sözleşme’nin 1’inci maddesinde yer alan adreslerini Tebligat Kanunu uyarınca tebligat adresi olarak kabul ve beyan ederler. Klinik, adres değişikliklerini Diştedavim’e bu değişiklikten en az 7 (yedi) gün önce tebliğ edilmediği takdirde, yukarıdaki adreslere yapılacak her türlü tebligat hukuken geçerli kabul edilir ve tüm hukuki sonuçlarını doğurur. İşbu Sözleşme kapsamında, Türk Ticaret Kanunu’nun 18’inci maddesi uyarınca tebligata gerek olmayan durumlarda, Sözleşme’ye ilişkin diğer bilgilendirme ve uyarılar, ve  Klinik’e gerçekleştirilecek bildirimler, Sözleşme’de veya Kullanım Koşulları’nda farklı kararlaştırılmadıkça, Klinik’in Platform’a kaydolurken bildirdiği e-posta adresi ve diğer iletişim adreslerine gerçekleştirilecektir. </p>
        
        <p className="mb-1 pb-1 text-md"><b>11.4</b> İşbu Sözleşme Türkiye Cumhuriyeti hukukuna tabidir. Bu Sözleşme’nin yorumundan ve uygulanmasından doğacak anlaşmazlıklarda İstanbul Mahkemeleri ve İcra Daireleri münhasıran yetkilidir.</p>
        
        <p className="mb-10 pb-10 text-md"><b>11.5</b> Bu Sözleşme’nin akdinden doğacak vergi ve diğer masraflar Klinik tarafından ödenecektir. Sözleşme, Platform üzerinden Klinik tarafından onaylandığı tarihte imzalanmış ve yürürlüğe girmiş kabul edilir.  </p>
        
    </div>
    );
  
  export default termsClinicRegister;